[settings]
trusted_config_paths = [
  "~/projects/flaudisio",
  "~/projects/labs",
]

[tools]
"aqua:simonwhitaker/gibo" = "3"
aws-cli = { version = "2.34", symlink_bins = "true" }
copier = "9"
cosign = "latest"
dive = "latest"
doppler = "latest"
fzf = "latest"
glab = "1"
go = "1.25"
granted = "latest"
hcl2json = "latest"
helm = "3"
jnv = "latest"
k9s = "latest"
kubectl = "1.34"
kubectx = "latest"
lazydocker = "latest"
node = "24"
"pipx:bump-my-version" = "1"
shellcheck = "latest"
uv = "latest"
yq = "4"

[tasks.bash]
description = "[Global] Run 'mise exec bash'"
alias = "enter"
run = "mise exec -- bash"
